[tool.poetry]
name = "notipus"
version = "0.1.0"
description = "A webhook service that sends enriched Shopify and Chargify notifications to Slack"
authors = ["Viktopia Studio <info@viktopia.io>"]
readme = "README.md"
packages = [
    { include = "app" }
]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.1.0"
requests = "^2.32.3"
shopifyapi = "^12.7.0"
python-dotenv = "^1.0.1"
sentry-sdk = {extras = ["flask"], version = "^2.19.2"}


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
ruff = "^0.8.4"
pre-commit = "^4.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
